### PR TITLE
fix two parameter mistakes

### PR DESCRIPTION
**Pull request by masihnajafi02**
D and N were used in the wrong places.
There are D vectors that are N-dimensional.

### CODE REVIEW

**Comment by masihnajafi02** [comment]
It was very confusing at the beginning and I thought it's the problem of only N and D being at wrong place but then I figured the problem is with the matrice's arrangement and N and D were in the right place at the beginning.

**Review by sinamazaheri1379 — APPROVED** [review]

**Review by sinamazaheri1379 — COMMENTED** [review]
Just the second commit is acceptable

**Review by sinamazaheri1379 — APPROVED** [review]

**Comment by mahsayazdani** [comment]
@masihnajafi02 Please revert unacceptable commits.

**Comment by masihnajafi02** [comment]
Reverted Successfully.

**Comment by mahsayazdani** [comment]
@masihnajafi02 Your pull request has been merged. Please email me your student ID.

**Pull request merged**
